### PR TITLE
Make the 'what' a bit clearer?

### PR DESCRIPTION
**Pull request by hawkz**

### CODE REVIEW

**Comment by tomkins** [comment]
Feels like a weird combination of marketing/instructions than just installation instructions.

**Comment by hawkz** [comment]
Was shooting for just a 'what is this' answer, I guess the 404 handler is a bit deep.

**Comment by tomkins** [comment]
Move it above **Installation**.

I think we need a paragraph or two explaining what is - a description which is focused at non-technical people, but something that Django developers would understand a bit more.

**Comment by hawkz** [comment]
Ok, so let's confirm the points of what it is..

- A djangonic front-end content management workflow
- Something you can build into your custom models
- Optional page manager if you want a flat pages style base

Anything else?

**Comment by tomkins** [comment]
Let's try again with this one once we've figured it out our unique offering.

**Pull request closed without merging**
